/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import lexico.Lexer;
import lexico.Token;

/**
 *
 * @author walte
 */
public class Main extends javax.swing.JFrame {
    private DefaultTableModel dtm;
    private String [][] data = {};
    private String titulos[] = {"TOKEN","LEXEMA","LINEA"};
  
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        dtm = new DefaultTableModel(data, titulos);
        tabla.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirArchivo = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        opciones = new javax.swing.JMenu();
        archivo = new javax.swing.JMenuItem();
        analizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        opciones.setText("Operaciones");

        archivo.setText("Archivo");
        archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoActionPerformed(evt);
            }
        });
        opciones.add(archivo);

        analizar.setText("Analizar");
        opciones.add(analizar);

        MenuBar.add(opciones);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos unicamente", "txt", "doc", "docx","js","html");
        abrirArchivo.setFileFilter(filter);
        int seleccion = abrirArchivo.showOpenDialog(tabla);
        
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File fichero = abrirArchivo.getSelectedFile();
                BufferedReader buffeRead = new BufferedReader(new FileReader(fichero));
                String linea = buffeRead.readLine();
                Lexer lexer = new Lexer(buffeRead);
                dtm.setRowCount(0);
                while (true) {
                    Token token = lexer.yylex();
                    if(!lexer.existenTokens()){
                        
                        break;
                    }else{
                        String data[] = { token.getLexema(), token.getToken(), Integer.toString(token.getLinea())};
                        dtm.addRow(data);
                        System.out.println(token.toString());
                    }
                }
                buffeRead.close();
            } catch (IOException ex) {
                 
            }
        }
    }//GEN-LAST:event_archivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JFileChooser abrirArchivo;
    private javax.swing.JMenuItem analizar;
    private javax.swing.JMenuItem archivo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu opciones;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
